### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by Thus0** [datamachine/telegram-pybot#1]
I'm using Ubuntu with python 2.0 (default) and python3.4

Compilation works fine and python3.4 is installed in sub directory .virtualenv/bin 

But when I use launch.sh, I have a python import error : 

thus0:~/usr/src/telegram-cli/datamachine/telegram-pybot$ ./launch.sh
Telegram-cli version 1.3.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type`show_license' for details.
Telegram-cli uses libtgl version 2.0.1
I: config dir=[/home/thus0/.telegram-cli]
ImportError: No module named site

... I seems like a virtualenv problem 
I have .virtualenv/lib/python3.4/site.py (no .pyc)

**Comment by Surye** [comment]
if you activate the virtualenv, and run 

```
./tg/bin/telegram-cli -k ./tg/tg-server.pub -Z ./runner.py -l 1
```

do you get the same error?
(And in py3 you won't get a pyc, they will be in __pycache__/, e.g. .virtualenv/lib/python3.4/__pycache__/site.cpython-34.pyc)

**Comment by Thus0** [comment]
Yes, I've already already activated but I have the same error. 
I've checked and I have indeed the .pyc in the cache...

**Comment by Thus0** [comment]
I found the problem : telegram-cli was compiled with python2.7. I just needed to install libpython3.4-dev and relaunch ./launch install so telegram-cli is compiled for python3.4 and I don't have the error anymore :)

**Comment by Surye** [comment]
Ah yes, more documentation needed for that to remind people. And maybe enforce it in the launch.sh script.
